use logos::Logos;

#[derive(Logos, Clone, Debug, PartialEq)]
#[logos(skip r"[ \t\r\n\f]+")]
pub enum TokenKind {
    #[token("(")]
    LeftParen,
    #[token(")")]
    RightParen,
    #[token("{")]
    LeftBrace,
    #[token("}")]
    RightBrace,
    #[token("[")]
    LeftSquare,
    #[token("]")]
    RightSquare,
    #[token("=")]
    Equals,
    #[token(",")]
    Comma,
    #[token(";")]
    Semicolon,
    #[token(":")]
    Colon,
    #[token(".")]
    Dot,
    #[regex("[_a-z][A-Za-z0-9_]*")]
    Name,
    #[regex("[A-Z][A-Za-z0-9_]*")]
    UpperName,
    #[regex("[0-9]+")]
    Number,
    #[token("func")]
    Func,
    #[token("cor")]
    Cor,
    #[token("let")]
    Let,
    #[token("set")]
    Set,
    #[token("if")]
    If,
    #[token("then")]
    Then,
    #[token("else")]
    Else,
    #[token("while")]
    While,
    #[token("struct")]
    Struct,
    #[token("True")]
    True,
    #[token("False")]
    False,
    #[token("!")]
    Bang,
    #[token("yield")]
    Yield,
    #[token("&")]
    Ampersand,
    #[token("*")]
    Star,
    #[token("+")]
    Plus,
    #[token("-")]
    Dash,
    #[token("/")]
    Slash,
    #[token("<<")]
    ShiftLeft,
    #[token(">>")]
    ShiftRight,
    #[token("|")]
    BitOr,
    #[token("~")]
    BitNot,
    #[token("^")]
    BitXor,
    #[token(">")]
    GreaterThan,
    #[token(">=")]
    GreaterEqual,
    #[token("<")]
    LessThan,
    #[token("<=")]
    LessEqual,
    #[token("==")]
    DoubleEquals,
    #[token("!=")]
    NotEquals,
    #[token("&&")]
    LogicAnd,
    #[token("||")]
    LogicOr,
}
